### ISSUE TITLE
Waiting for review

### ISSUE THREAD

**Issue by nguyentrungdev** [nguyentrungdev/TipCal#1]
My app is complete. Could you please review it @chug2k

**Comment by chug2k** [comment]
Sorry - you haven't completed all the required tasks:

> - [ ] Required: User can enter a bill amount, choose a tip percentage, and see the tip and total values.
>   - [ ] Required: Settings page to change the default tip percentage. 

You need a settings page to change the **default** tip percentage, which is the tip percentage selected when you first open the app. So far I only see one screen.

For an example of what I mean, check out the GIF from this student's submission: https://github.com/terryndb/Tipper. 

Once you've finished this, let me know. **I cannot accept you into the class until you finish the required tasks**. If you have questions, please feel free to ask here or via email (sang {at} coderschool.vn). We can also meet in person somewhere near D1/D3 if you need more help! I hope to see you in the class.

/cc @marcusellison @harley @minhchau273
